spring:
  profiles:
    active: local
  devtools:
    restart:
      enabled: true
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/static/
  datasource:
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/weather?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: weatherman
    password: 293702
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

mybatis:
  mapper-locations: /mapper/**/*.xml

logging:
  level:
    com:
      weather: DEBUG

jwt:
  secret: eyJhbGciOiJIUzUxMiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTYzMzg1Nzc3OSwiaWF0IjoxNjMzODU3Nzc5fQ.pBd5TTFnEFqqpC3w3kUVRTcvXqSEzK2MpCaZcAIOo6f890LW7rOqbJT1l5i0tHAlkMlVbBosmc9hwSr4RfEFfQ